//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTAformApp.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class validation_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal validation_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTAformApp.App_LocalResources.validation.aspx", typeof(validation_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap adhesivocristal_90 {
            get {
                object obj = ResourceManager.GetObject("adhesivocristal_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar Cuenta&lt;/a&gt;&lt;/strong&gt;&lt;/p&gt;&lt;/ul&gt;&lt;/strong&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;.
        /// </summary>
        public static string EmailAccountID {
            get {
                return ResourceManager.GetString("EmailAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no puede acceder con el enlace anterior copie y pegue la siguiente dirección en su navegador web: .
        /// </summary>
        public static string EmailAlternativeURL {
            get {
                return ResourceManager.GetString("EmailAlternativeURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/strong&gt;:&lt;/p&gt;&lt;p&gt;Su solicitud ha sido procesada con éxito. Para poder acceder al &lt;i&gt;Servicio de pago por móvil e internet del Estacionamiento de Mugipark&quot; &lt;/i&gt;debe activar su cuenta pulsando sobre el siguiente enlace: &lt;strong&gt;.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Recuerde:&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;em&gt;Para su &lt;b&gt;identificación en el servicio&lt;/b&gt;, es necesario que &lt;b&gt;solicite su distintivo&lt;/b&gt; al controlador mas cercano, y lo adhiera en el parabrisas de su vehículo.&lt;/em&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;em&gt;&lt;b&gt;Esta identificación es necesaria ya que usted no dispone de tique físico.&lt;b&gt;&lt;/em&gt;&lt;/p&gt;
        ///&lt;hr /&gt;.
        /// </summary>
        public static string EmailBodyDistinctiveMsg {
            get {
                return ResourceManager.GetString("EmailBodyDistinctiveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;&lt;p&gt;&lt;strong&gt;Advertencia:&lt;/strong&gt; Una vez activada su cuenta de usuario, es recomendable que modifique la contraseña que le ha sido asignada. Puede hacerlo desde &lt;a href=&quot;http://www.mugipark.com/&quot; target=&quot;_blank&quot;&gt;Mugipark Web&lt;/a&gt;, accediendo a sus datos mediante dicha cuenta de usuario.&lt;/p&gt;.
        /// </summary>
        public static string EmailBodyPrinterForm {
            get {
                return ResourceManager.GetString("EmailBodyPrinterForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Datos usuario:&lt;br/&gt;&lt;ul&gt;&lt;li&gt;Usuario: [NIF/CIF que facilitó en el formulario de Suscripción]&lt;/li&gt;&lt;li&gt;Contraseña: .
        /// </summary>
        public static string EmailBodyPrinterFormPassword {
            get {
                return ResourceManager.GetString("EmailBodyPrinterFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si tiene alguna duda o consulta, puede contactar en: &lt;p&gt;Mugipark&lt;br&gt;.
        /// </summary>
        public static string EmailFeet {
            get {
                return ResourceManager.GetString("EmailFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Estimad@ Sr./Sra. &lt;strong&gt;.
        /// </summary>
        public static string EmailHead {
            get {
                return ResourceManager.GetString("EmailHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de la Suscripción.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al realizar la suscripción..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExceptionModify {
            get {
                return ResourceManager.GetString("ExceptionModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , su información ha sido procesada con éxito para poder acceder al &lt;i&gt;&quot;Servicio de pago por móvil e internet del estacionamiento de Mugipark&quot;&lt;/i&gt;..
        /// </summary>
        public static string locDescription {
            get {
                return ResourceManager.GetString("locDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los Datos de su suscripción se le enviarán a su cuenta de correo:.
        /// </summary>
        public static string locDescriptionEmail {
            get {
                return ResourceManager.GetString("locDescriptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grácias por su confianza..
        /// </summary>
        public static string locDescriptionFeet {
            get {
                return ResourceManager.GetString("locDescriptionFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr./Sra: .
        /// </summary>
        public static string locDescriptionHead {
            get {
                return ResourceManager.GetString("locDescriptionHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información ha sido procesada con éxito. Sus datos han sido actualizados..
        /// </summary>
        public static string locDescriptionModify {
            get {
                return ResourceManager.GetString("locDescriptionModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformidad de Suscripción.
        /// </summary>
        public static string locSubTitle {
            get {
                return ResourceManager.GetString("locSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificación de Datos.
        /// </summary>
        public static string locSubTitleModify {
            get {
                return ResourceManager.GetString("locSubTitleModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio de pago remoto del estacionamiento de Mugipark.
        /// </summary>
        public static string locTitle {
            get {
                return ResourceManager.GetString("locTitle", resourceCulture);
            }
        }
    }
}
